import { MIN_SIGNATURE_LENGTH, SKIP_THOUGHT_SIGNATURE } from "./constants.js"

/** Host settings and diagnostics supplied to the pure signature filter. */
export interface ThinkingFilterOptions {
  keepThinking?: boolean
  onDebug?: (message: string) => void
}

/**
 * Checks if a part is a thinking/reasoning block (Anthropic or Gemini style).
 */
function isThinkingPart(part: Record<string, unknown>): boolean {
  return (
    part.type === "thinking" ||
    part.type === "redacted_thinking" ||
    part.type === "reasoning" ||
    part.thinking !== undefined ||
    part.thought === true
  )
}

/**
 * Checks if a part has a signature field (thinking block signature).
 * Used to detect foreign thinking blocks that might have unknown type values.
 */
function hasSignatureField(part: Record<string, unknown>): boolean {
  return part.signature !== undefined || part.thoughtSignature !== undefined
}

/**
 * Checks if a part is a tool block (tool_use or tool_result).
 * Tool blocks must never be filtered - they're required for tool call/result pairing.
 * Handles multiple formats:
 * - Anthropic: { type: "tool_use" }, { type: "tool_result", tool_use_id }
 * - Nested: { tool_result: { tool_use_id } }, { tool_use: { id } }
 * - Gemini: { functionCall }, { functionResponse }
 */
function isToolBlock(part: Record<string, unknown>): boolean {
  return (
    part.type === "tool_use" ||
    part.type === "tool_result" ||
    part.tool_use_id !== undefined ||
    part.tool_call_id !== undefined ||
    part.tool_result !== undefined ||
    part.tool_use !== undefined ||
    part.toolUse !== undefined ||
    part.functionCall !== undefined ||
    part.functionResponse !== undefined
  )
}

/**
 * Unconditionally strips ALL thinking/reasoning blocks from a content array.
 * Used for Claude models to avoid signature validation errors entirely.
 * Claude will generate fresh thinking for each turn.
 */
function stripAllThinkingBlocks(contentArray: any[]): any[] {
  return contentArray.filter((item) => {
    if (!item || typeof item !== "object") return true
    if (isToolBlock(item)) return true
    if (isThinkingPart(item)) return false
    if (hasSignatureField(item)) return false
    return true
  })
}

/**
 * Removes trailing thinking blocks from a content array.
 * Claude API requires that assistant messages don't end with thinking blocks.
 * Only removes unsigned thinking blocks; preserves those with valid signatures.
 */
function removeTrailingThinkingBlocks(
  contentArray: any[],
  sessionId?: string,
  getCachedSignatureFn?: (sessionId: string, text: string) => string | undefined,
): any[] {
  const result = [...contentArray]

  while (result.length > 0 && isThinkingPart(result[result.length - 1])) {
    const part = result[result.length - 1]
    const isValid =
      sessionId && getCachedSignatureFn
        ? isOurCachedSignature(part as Record<string, unknown>, sessionId, getCachedSignatureFn)
        : hasValidSignature(part as Record<string, unknown>)
    if (isValid) {
      break
    }
    result.pop()
  }

  return result
}

/**
 * Checks if a thinking part has a valid signature.
 * A valid signature is a non-empty string with at least 50 characters.
 */
function hasValidSignature(part: Record<string, unknown>): boolean {
  const signature = part.thought === true ? part.thoughtSignature : part.signature
  return typeof signature === "string" && signature.length >= 50
}

/**
 * Gets the signature from a thinking part, if present.
 */
function getSignature(part: Record<string, unknown>): string | undefined {
  const signature = part.thought === true ? part.thoughtSignature : part.signature
  return typeof signature === "string" ? signature : undefined
}

/**
 * Checks if a thinking part's signature was generated by our plugin (exists in our cache).
 * This prevents accepting signatures from other providers (e.g., direct Anthropic API, OpenAI)
 * which would cause "Invalid signature" errors when sent to Antigravity Claude.
 */
function isOurCachedSignature(
  part: Record<string, unknown>,
  sessionId: string | undefined,
  getCachedSignatureFn: ((sessionId: string, text: string) => string | undefined) | undefined,
): boolean {
  if (!sessionId || !getCachedSignatureFn) {
    return false
  }

  const text = getThinkingText(part)
  if (!text) {
    return false
  }

  const partSignature = getSignature(part)
  if (!partSignature) {
    return false
  }

  const cachedSignature = getCachedSignatureFn(sessionId, text)
  return cachedSignature === partSignature
}

/**
 * Gets the text content from a thinking part.
 */
function getThinkingText(part: Record<string, unknown>): string {
  if (typeof part.text === "string") return part.text
  if (typeof part.thinking === "string") return part.thinking

  if (part.text && typeof part.text === "object") {
    const maybeText = (part.text as any).text
    if (typeof maybeText === "string") return maybeText
  }

  if (part.thinking && typeof part.thinking === "object") {
    const maybeText = (part.thinking as any).text ?? (part.thinking as any).thinking
    if (typeof maybeText === "string") return maybeText
  }

  return ""
}

/**
 * Recursively strips cache_control and providerOptions from any object.
 * These fields can be injected by SDKs, but Claude rejects them inside thinking blocks.
 */
function stripCacheControlRecursively(obj: unknown): unknown {
  if (obj === null || obj === undefined) return obj
  if (typeof obj !== "object") return obj
  if (Array.isArray(obj)) return obj.map((item) => stripCacheControlRecursively(item))

  const result: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
    if (key === "cache_control" || key === "providerOptions") continue
    result[key] = stripCacheControlRecursively(value)
  }
  return result
}

/**
 * Sanitizes a thinking part by keeping only the allowed fields.
 * In particular, ensures `thinking` is a string (not an object with cache_control).
 * Returns null if the thinking block has no valid content.
 */
function sanitizeThinkingPart(part: Record<string, unknown>): Record<string, unknown> | null {
  // Gemini-style thought blocks: { thought: true, text, thoughtSignature }
  if (part.thought === true) {
    let textContent: unknown = part.text
    if (typeof textContent === "object" && textContent !== null) {
      const maybeText = (textContent as any).text
      textContent = typeof maybeText === "string" ? maybeText : undefined
    }

    const hasContent = typeof textContent === "string" && textContent.trim().length > 0
    if (!hasContent && !part.thoughtSignature) {
      return null
    }

    const sanitized: Record<string, unknown> = { thought: true }
    if (textContent !== undefined) sanitized.text = textContent
    if (part.thoughtSignature !== undefined) sanitized.thoughtSignature = part.thoughtSignature
    return sanitized
  }

  // Anthropic-style thinking/redacted_thinking blocks: { type: "thinking"|"redacted_thinking", thinking, signature }
  if (part.type === "thinking" || part.type === "redacted_thinking" || part.thinking !== undefined) {
    let thinkingContent: unknown = part.thinking ?? part.text
    if (thinkingContent !== undefined && typeof thinkingContent === "object" && thinkingContent !== null) {
      const maybeText = (thinkingContent as any).text ?? (thinkingContent as any).thinking
      thinkingContent = typeof maybeText === "string" ? maybeText : undefined
    }

    const hasContent = typeof thinkingContent === "string" && thinkingContent.trim().length > 0
    if (!hasContent && !part.signature) {
      return null
    }

    const sanitized: Record<string, unknown> = {
      type: part.type === "redacted_thinking" ? "redacted_thinking" : "thinking",
    }
    if (thinkingContent !== undefined) sanitized.thinking = thinkingContent
    if (part.signature !== undefined) sanitized.signature = part.signature
    return sanitized
  }

  // Reasoning blocks (OpenCode format): { type: "reasoning", text, signature }
  if (part.type === "reasoning") {
    let textContent: unknown = part.text
    if (typeof textContent === "object" && textContent !== null) {
      const maybeText = (textContent as any).text
      textContent = typeof maybeText === "string" ? maybeText : undefined
    }

    const hasContent = typeof textContent === "string" && textContent.trim().length > 0
    if (!hasContent && !part.signature) {
      return null
    }

    const sanitized: Record<string, unknown> = { type: "reasoning" }
    if (textContent !== undefined) sanitized.text = textContent
    if (part.signature !== undefined) sanitized.signature = part.signature
    return sanitized
  }

  // Fallback: strip cache_control recursively.
  return stripCacheControlRecursively(part) as Record<string, unknown>
}

/** Finds the final assistant turn for one provider message representation. */
function findLastAssistantIndex(contents: any[], roleValue: "model" | "assistant"): number {
  for (let i = contents.length - 1; i >= 0; i--) {
    const content = contents[i]
    if (content && typeof content === "object" && content.role === roleValue) {
      return i
    }
  }
  return -1
}

/** Filters one content array according to model and signature ownership rules. */
function filterContentArray(
  contentArray: any[],
  sessionId?: string,
  getCachedSignatureFn?: (sessionId: string, text: string) => string | undefined,
  isClaudeModel?: boolean,
  isLastAssistantMessage: boolean = false,
  options: ThinkingFilterOptions = {},
): any[] {
  // For Claude models, strip thinking blocks by default for reliability
  // User can opt-in to keep thinking via config: { "keep_thinking": true }
  if (isClaudeModel && !options.keepThinking) {
    return stripAllThinkingBlocks(contentArray)
  }

  const filtered: any[] = []

  for (const item of contentArray) {
    if (!item || typeof item !== "object") {
      filtered.push(item)
      continue
    }

    if (isToolBlock(item)) {
      if (!isClaudeModel) {
        filtered.push(item)
        continue
      }

      const sanitizedToolBlock = { ...(item as Record<string, unknown>) }
      delete (sanitizedToolBlock as any).signature
      delete (sanitizedToolBlock as any).thoughtSignature
      delete (sanitizedToolBlock as any).thought_signature
      delete (sanitizedToolBlock as any).thought
      filtered.push(sanitizedToolBlock)
      continue
    }

    const isThinking = isThinkingPart(item)
    const hasSignature = hasSignatureField(item)

    if (!isThinking && !hasSignature) {
      filtered.push(item)
      continue
    }

    if (isClaudeModel && (isThinking || hasSignature)) {
      const thinkingText = getThinkingText(item) || ""
      if (isOurCachedSignature(item as Record<string, unknown>, sessionId, getCachedSignatureFn)) {
        const sanitized = sanitizeThinkingPart(item as Record<string, unknown>)
        if (sanitized) filtered.push(sanitized)
        continue
      }

      if (sessionId && getCachedSignatureFn && thinkingText) {
        const cachedSignature = getCachedSignatureFn(sessionId, thinkingText)
        if (cachedSignature && cachedSignature.length >= MIN_SIGNATURE_LENGTH) {
          const restoredPart = { ...(item as Record<string, unknown>) }
          if (restoredPart.thought === true) {
            restoredPart.thoughtSignature = cachedSignature
          } else {
            restoredPart.signature = cachedSignature
          }
          const sanitized = sanitizeThinkingPart(restoredPart)
          if (sanitized) filtered.push(sanitized)
          continue
        }
      }

      const sentinelPart = {
        type: item.type === "redacted_thinking" ? "redacted_thinking" : "thinking",
        thinking: thinkingText,
        signature: SKIP_THOUGHT_SIGNATURE,
      }
      filtered.push(sentinelPart)
      continue
    }

    // For the LAST assistant message with thinking blocks:
    // - If signature is OUR cached signature, pass through unchanged
    // - Otherwise inject sentinel to bypass Antigravity validation
    // NOTE: We can't trust signatures just because they're >= 50 chars - Claude returns
    // its own signatures which are long but invalid for Antigravity.
    if (isLastAssistantMessage && (isThinking || hasSignature)) {
      // First check if it's our cached signature
      if (isOurCachedSignature(item, sessionId, getCachedSignatureFn)) {
        const sanitized = sanitizeThinkingPart(item)
        if (sanitized) filtered.push(sanitized)
        continue
      }

      // Not our signature (or no signature) - inject sentinel
      const thinkingText = getThinkingText(item) || ""
      const existingSignature = item.signature || item.thoughtSignature
      const signatureInfo = existingSignature
        ? `foreign signature (${String(existingSignature).length} chars)`
        : "no signature"
      options.onDebug?.(`Injecting sentinel for last-message thinking block with ${signatureInfo}`)
      const sentinelPart = {
        type: item.type || "thinking",
        thinking: thinkingText,
        signature: SKIP_THOUGHT_SIGNATURE,
      }
      filtered.push(sentinelPart)
      continue
    }

    if (isOurCachedSignature(item, sessionId, getCachedSignatureFn)) {
      const sanitized = sanitizeThinkingPart(item)
      if (sanitized) filtered.push(sanitized)
      continue
    }

    if (sessionId && getCachedSignatureFn) {
      const text = getThinkingText(item)
      if (text) {
        const cachedSignature = getCachedSignatureFn(sessionId, text)
        if (cachedSignature && cachedSignature.length >= MIN_SIGNATURE_LENGTH) {
          const restoredPart = { ...item }
          if ((item as any).thought === true) {
            ;(restoredPart as any).thoughtSignature = cachedSignature
          } else {
            ;(restoredPart as any).signature = cachedSignature
          }
          const sanitized = sanitizeThinkingPart(restoredPart as Record<string, unknown>)
          if (sanitized) filtered.push(sanitized)
          continue
        }
      }
    }
  }

  return filtered
}

/**
 * Filters thinking blocks from contents unless the signature matches our cache.
 * Attempts to restore signatures from cache for thinking blocks that lack signatures.
 */
export function filterUnsignedThinkingBlocks(
  contents: any[],
  sessionId?: string,
  getCachedSignatureFn?: (sessionId: string, text: string) => string | undefined,
  isClaudeModel?: boolean,
  options: ThinkingFilterOptions = {},
): any[] {
  const lastAssistantIdx = findLastAssistantIndex(contents, "model")

  return contents.map((content: any, idx: number) => {
    if (!content || typeof content !== "object") {
      return content
    }

    const isLastAssistant = idx === lastAssistantIdx

    if (Array.isArray((content as any).parts)) {
      const filteredParts = filterContentArray(
        (content as any).parts,
        sessionId,
        getCachedSignatureFn,
        isClaudeModel,
        isLastAssistant,
        options,
      )

      const trimmedParts =
        (content as any).role === "model" && !isClaudeModel
          ? removeTrailingThinkingBlocks(filteredParts, sessionId, getCachedSignatureFn)
          : filteredParts

      return { ...content, parts: trimmedParts }
    }

    if (Array.isArray((content as any).content)) {
      const isAssistantRole = (content as any).role === "assistant"
      const isLastAssistantContent =
        idx === lastAssistantIdx || (isAssistantRole && idx === findLastAssistantIndex(contents, "assistant"))

      const filteredContent = filterContentArray(
        (content as any).content,
        sessionId,
        getCachedSignatureFn,
        isClaudeModel,
        isLastAssistantContent,
        options,
      )

      const trimmedContent =
        isAssistantRole && !isClaudeModel
          ? removeTrailingThinkingBlocks(filteredContent, sessionId, getCachedSignatureFn)
          : filteredContent

      return { ...content, content: trimmedContent }
    }

    return content
  })
}

/**
 * Filters thinking blocks from Anthropic-style messages[] payloads using cached signatures.
 */
export function filterMessagesThinkingBlocks(
  messages: any[],
  sessionId?: string,
  getCachedSignatureFn?: (sessionId: string, text: string) => string | undefined,
  isClaudeModel?: boolean,
  options: ThinkingFilterOptions = {},
): any[] {
  const lastAssistantIdx = findLastAssistantIndex(messages, "assistant")

  return messages.map((message: any, idx: number) => {
    if (!message || typeof message !== "object") {
      return message
    }

    if (Array.isArray((message as any).content)) {
      const isAssistantRole = (message as any).role === "assistant"
      const isLastAssistant = isAssistantRole && idx === lastAssistantIdx

      const filteredContent = filterContentArray(
        (message as any).content,
        sessionId,
        getCachedSignatureFn,
        isClaudeModel,
        isLastAssistant,
        options,
      )

      const trimmedContent =
        isAssistantRole && !isClaudeModel
          ? removeTrailingThinkingBlocks(filteredContent, sessionId, getCachedSignatureFn)
          : filteredContent

      return { ...message, content: trimmedContent }
    }

    return message
  })
}

/** Recursively filters provider message arrays in a mutable request payload. */
export function deepFilterThinkingBlocks(
  payload: unknown,
  sessionId?: string,
  getCachedSignatureFn?: (sessionId: string, text: string) => string | undefined,
  isClaudeModel?: boolean,
  options: ThinkingFilterOptions = {},
): unknown {
  const visited = new WeakSet<object>()

  /** Recursively visits nested provider envelopes once. */
  const walk = (value: unknown): void => {
    if (!value || typeof value !== "object") {
      return
    }

    if (visited.has(value as object)) {
      return
    }

    visited.add(value as object)

    if (Array.isArray(value)) {
      value.forEach((item) => walk(item))
      return
    }

    const obj = value as Record<string, unknown>

    if (Array.isArray(obj.contents)) {
      obj.contents = filterUnsignedThinkingBlocks(
        obj.contents as any[],
        sessionId,
        getCachedSignatureFn,
        isClaudeModel,
        options,
      )
    }

    if (Array.isArray(obj.messages)) {
      obj.messages = filterMessagesThinkingBlocks(
        obj.messages as any[],
        sessionId,
        getCachedSignatureFn,
        isClaudeModel,
        options,
      )
    }

    Object.keys(obj).forEach((key) => walk(obj[key]))
  }

  walk(payload)
  return payload
}
