/** Compatibility exports for callers of the previous transform module path. */
export {
  applyClaudeTransforms,
  applyGeminiTransforms,
  appendClaudeThinkingHint,
  buildClaudeThinkingConfig,
  buildGemini25ThinkingConfig,
  buildGemini3ThinkingConfig,
  buildImageGenerationConfig,
  configureClaudeToolConfig,
  ensureClaudeMaxOutputTokens,
  getCrossModelFamily,
  getModelFamily,
  isClaudeModel,
  isClaudeThinkingModel,
  isGemini25Model,
  isGemini3Model,
  isGeminiModel,
  isImageGenerationModel,
  normalizeClaudeTools,
  normalizeGeminiTools,
  resolveAntigravityModel,
  resolveModelWithTier,
  resolveModelWithVariant,
  sanitizeCrossModelPayload,
  sanitizeCrossModelPayloadInPlace,
  stripClaudeThinkingFields,
  stripGeminiThinkingMetadata,
  CLAUDE_INTERLEAVED_THINKING_HINT,
  CLAUDE_THINKING_MAX_OUTPUT_TOKENS,
  GEMINI_3_THINKING_LEVELS,
  MODEL_ALIASES,
  THINKING_TIER_BUDGETS,
} from "../../modules/inference/index.js"
export type {
  ClaudeTransformOptions,
  ClaudeTransformResult,
  GeminiTransformOptions,
  GeminiTransformResult,
  GoogleSearchConfig,
  ImageConfig,
  ModelFamily,
  RequestPayload,
  ResolvedModel,
  SanitizerOptions,
  ThinkingConfig,
  ThinkingTier,
  TransformContext,
  TransformDebugInfo,
  TransformResult,
  VariantConfig,
} from "../../modules/inference/index.js"
