/** Provider identifier shared between the plugin loader and credential store. */
export const ANTIGRAVITY_PROVIDER_ID = "antigravity"

export {
  ANTIGRAVITY_CLIENT_ID,
  ANTIGRAVITY_CLIENT_SECRET,
  ANTIGRAVITY_SCOPES,
  ANTIGRAVITY_REDIRECT_URI,
  ANTIGRAVITY_ENDPOINT_DAILY,
  ANTIGRAVITY_ENDPOINT_PROD,
  ANTIGRAVITY_ENDPOINT_FALLBACKS,
  ANTIGRAVITY_LOAD_ENDPOINTS,
  ANTIGRAVITY_ENDPOINT,
  ANTIGRAVITY_DEFAULT_PROJECT_ID,
  ANTIGRAVITY_VERSION_FALLBACK,
  getAntigravityVersion,
  setAntigravityVersion,
  ANTIGRAVITY_VERSION,
  getAntigravityHeaders,
  ANTIGRAVITY_HEADERS,
  ANTIGRAVITY_AUTH_USER_AGENT,
  getRandomizedHeaders,
} from "./adapters/antigravity/constants.js"
export type { HeaderSet } from "./adapters/antigravity/constants.js"

export {
  ANTIGRAVITY_SYSTEM_INSTRUCTION,
  CLAUDE_DESCRIPTION_PROMPT,
  CLAUDE_TOOL_SYSTEM_INSTRUCTION,
  EMPTY_SCHEMA_PLACEHOLDER_NAME,
  EMPTY_SCHEMA_PLACEHOLDER_DESCRIPTION,
  SKIP_THOUGHT_SIGNATURE,
} from "./modules/inference/index.js"
